
  const game_thumbnails = [
    {
      id: "Bus-Rush", 
      content: '/Thumbnails/BusRush.png', 
      name: "Bus Rush", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A time-based arcade racing game where players must reach the final stop while picking up as many passengers as possible. The game grades players on punctuality and passenger count, with performance bonuses tied to how fast they complete their route, and how little damage their vehicle sustains.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"], 
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"], 
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Citizen-Jane", 
      content: './thumbnails/CitizenJane.png', 
      name: "Citizen Jane", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "Play as private investigator Jane, and  solve a high profile murder. Traverse through comic panels and obtain clues,  and combine them to solve the mystery.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"],
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Endzone", 
      content: './thumbnails/Endzone.png', 
      name: "Endzone", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "An arcade style sports survival game. Avoid opposing defenders in each region of the football field and reach the opponents end zone to win the game.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"],
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Flipped-Out", 
      content: './thumbnails/FlippedOut.jpg', 
      name: "Flipped Out", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A fast-paced mobile memory matching game with both solo and competitive play, player trophies, and a global leaderboard", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Moonlight-Paws", 
      content: './thumbnails/MoonlightPaws.png', 
      name: "Moonlight Paws", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A puzzle-based narrative experience focused on shape recognition and spatial navigation. Each level presents a hint describing a specific shape. Players must read the hint carefully, choose a direction to move, and explore the space to find the correct match.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Neon-Vendetta", content: './thumbnails/NeonVendetta.png', 
      name: "Neon Vendetta", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "Experience a 2D cyberpunk action platformer heavily inspired by SpeedRunners, and Vector. Each level introduces new twists on mechanics from intense boss fights to platformer minigames.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Pick-Your-Poison", content: './thumbnails/PYP.png', 
      name: "Pick Your Poison", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A survival taste-testing game where players must test dishes for poison before serving them. Tasting a dish will reveal ingredients on a one-per bite basis, players must must control their bites to avoid eating poison, and tasting too much before serving.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Upperdut", 
      content: './thumbnails/Upperdut.png', 
      name: "Upperdut", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A unique take on the platform fighter genre, Upperdut is a 2-player game where instead of fighting each other, players work together! Conquer the heights of the gym as you work your way up to the top.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
    {
      id: "Othello", 
      content: './thumbnails/Othello.png', 
      name: "Othello", 
      role: "Game Programmer | Designer",
      engine: "Unity",
      team: "4",
      page: "https://nova-so1.itch.io/bus-rush",
      desc: "A digital recreation of the board game Othello built entirely in Java using JavaFX for the GUI.  this application allows for Human vs. Human, Human vs. CPU, and CPU vs. CPU gameplay.", 
      video: "https://github.com/Mame-Mor-M/Mbong-Art-Portfolio/releases/download/Animation/Flux_Intro.mp4",
      gallery: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemImage: ["/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png", "/Thumbnails/BusRush.png"],
      systemName: ["System 1", "System 2", "System 3"],
      systemDesc: ["BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING", "BUS RUSH BUS AND RUSHING"]
    },
]

export default game_thumbnails;